apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: directus
  name: directus
spec:
  type: LoadBalancer
  ports:
  - name: "8055"
    port: 8055
    targetPort: 8055
  selector:
    io.kompose.service: directus
status:
  loadBalancer: {}
