kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-directus
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: directus-pvc-directus
  labels:
    app: directus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi